---

- name: Clean Up Packages and System Files
  hosts: all
  become: true
  tasks:

    - name: Remove unused packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Clean apt cache (Debian/Ubuntu)
      ansible.builtin.apt:
        autoclean: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Remove unused packages (Fedora/RHEL/CentOS)
      ansible.builtin.dnf:
        autoremove: yes
      when: ansible_distribution in ["Fedora", "RHEL"]

    - name: Clean dnf metadata cache (Fedora/RHEL/CentOS)
      ansible.builtin.command: dnf clean all
      when: ansible_distribution in ["Fedora", "RHEL"]

    - name: Remove old journal logs older than 2 weeks
      ansible.builtin.command: journalctl --vacuum-time=2weeks
      when: ansible_service_mgr == "systemd"

    - name: Remove old crash dumps
      ansible.builtin.file:
        path: /var/crash
        state: absent
      ignore_errors: yes
