---
- name: Apply Required Reboots
  hosts: all
  become: true
  tasks:

    - name: Check if reboot is required (Debian/Ubuntu)
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_debian

    - name: Apply Required Reboots (Debian/Ubuntu)
      when:
        - ansible_distribution in ["Debian", "Ubuntu"]
        - reboot_required_debian.stat.exists
      ansible.builtin.reboot:

    - name: Ensure yum-utils is installed (Fedora/RHEL)
      when: ansible_distribution in ["Fedora", "RHEL"]
      ansible.builtin.dnf:
        name: yum-utils
        state: present
  
    - name: Check if reboot is required (Fedora/RHEL)
      when: ansible_distribution in ["Fedora", "RHEL"]
      ansible.builtin.shell:
        cmd: "needs-restarting -r"
      register: needs_restarting
      changed_when: needs_restarting.rc == 1
      failed_when: needs_restarting.rc != 1 and needs_restarting.rc != 0

    - name: Apply Required Reboots (Fedora/RHEL)
      when: 
        - ansible_distribution in ["Fedora", "RHEL", "CentOS"]
        - needs_restarting.rc == 1
      ansible.builtin.reboot:

