---
- name: Configure Prometheus Node Exporter
  hosts: all
  become: true
  tasks:

    - name: Ensure prometheus-node-exporter is installed (Debian/Ubuntu)
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present

    - name: Ensure node-exporter is installed (Fedora/RHEL)
      when: ansible_distribution in ["Fedora", "RHEL"]
      ansible.builtin.dnf:
        name: node-exporter
        state: present

    - name: Ensure prometheus-node-exporter is running and enabled (Debian/Ubuntu)
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.bultin.systemd:
        name: prometheus-node-exporter
        state: running
        enabled: true

    - name: Ensure prometheus-node-exporter is running and enabled (Debian/Ubuntu)
      when: ansible_distribution in ["Fedora", "RHEL"]
      ansible.bultin.systemd:
        name: node-exporter
        state: running
        enabled: true
