---
- name: Configure Prometheus Node Exporter
  hosts: all
  become: true
  tasks:

    - name: Ensure prometheus-node-exporter is installed (Debian/Ubuntu)
      when: ansible_distribution in ["Debian", "Ubuntu"]
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present

    - name: Ensure node-exporter is installed (Fedora/RHEL)
      when: ansible_distribution in ["Fedora", "RHEL"]
      ansible.builtin.dnf:
        name: node-exporter
        state: present

    - name: Ensure prometheus-node-exporter is running and enabled
      ansible.builtin.systemd_service:
        name: prometheus-node-exporter
        state: started
        enabled: true

    - name: Ensure port 9100 is open
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        state: enabled
        immediate: true
