---
- name: Reboot if required
  hosts: all
  become: true
  tasks:

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Reboot the server (Debian/Ubuntu)
      reboot:
      when: reboot_required.stat.exists and ansible_distribution in ["Debian", "Ubuntu"]

    - name: Check if reboot is required (Fedora/RHEL/CentOS)
      command: needs-restarting -r # requires dnf-utils package
      register: reboot_required
      failed_when: reboot_required.rc not in [0, 1]
      changed_when: reboot_required.rc == 1
      when: ansible_distribution in ["Fedora", "RHEL", "CentOS"]

    - name: Reboot the server (Fedora/RHEL/CentOS)
      reboot:
      when: reboot_required.rc == 1 and ansible_distribution in ["Fedora", "RHEL", "CentOS"]