---
- name: Reboot if required
  hosts: all
  become: true
  tasks:

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_debian
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Apply Required Reboots (Debian/Ubuntu)
      reboot:
      when: 
        - reboot_required_debian.stat.exists
        - ansible_distribution in ["Debian", "Ubuntu"]
