---
- name: Reboot if required
  hosts: all
  become: true
  tasks:

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Reboot the server (Debian/Ubuntu)
      reboot:
      when: reboot_required.stat.exists and ansible_distribution in ["Debian", "Ubuntu"]

    - name: Check if reboot is required (Fedora/RHEL/CentOS)
      shell: "needs-restarting -r"
      register: reboot_required
      changed_when: false
      failed_when: reboot_required.rc != 0 and reboot_required.rc != 1
      check_mode: false

    - name: Reboot the server (Fedora/RHEL/CentOS)
      reboot:
        reboot_time: 30
      when: reboot_required.rc == 1 and ansible_distribution in ["Fedora", "RHEL", "CentOS"]