---
- name: Reboot if required
  hosts: all
  become: true
  tasks:

    - name: Check if reboot is required (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required_debian
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Apply Required Reboots (Debian/Ubuntu)
      reboot:
      when: 
        - ansible_distribution in ["Debian", "Ubuntu"]
        - reboot_required_debian.stat.exists

    - name: Install yum-utils if needed (Fedora/RHEL/CentOS)
      ansible.builtin.dnf:
        name: yum-utils
        state: present
      when:
        - ansible_distribution in ["Fedora", "RHEL", "CentOS"]
  
    - name: Check if reboot is required (Fedora/RHEL/CentOS)
      ansible.builtin.shell:
        cmd: "needs-restarting -r -s"
      register: needs_restarting
      changed_when: needs_restarting.rc == 1
      when: ansible_distribution in ["Fedora", "RHEL", "CentOS"]

    - name: Apply Required Reboots (Fedora/RHEL/CentOS)
      ansible.builtin.reboot:
      when: 
        - ansible_distribution in ["Fedora", "RHEL", "CentOS"]
        - needs_restarting.rc == 1
