---

- name: Update and Upgrade Packages
  hosts: all
  become: true  
  tasks:

    - name: Update apt packages (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Upgrade apt packages (Debian/Ubuntu)
      apt:
        upgrade: dist
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Update dnf packages (Fedora/RHEL/CentOS)
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution in ["Fedora", "RHEL", "CentOS"]

- name: Reboot Required Hosts
  hosts: all
  become: true
  tasks:
    - name: Check if reboot is needed (Debian/Ubuntu)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Reboot if required (Debian/Ubuntu)
      reboot:
      when: reboot_required.stat.exists and ansible_distribution in ["Debian", "Ubuntu"]

    - name: Check if reboot is needed (Fedora/RHEL/CentOS)
      command: needs-restarting -r
      register: reboot_required_centos
      failed_when: reboot_required_centos.rc not in [0, 1]
      changed_when: reboot_required_centos.rc == 1
      when: ansible_distribution in ["Fedora", "RHEL", "CentOS"]

    - name: Reboot if required (Fedora/RHEL/CentOS)
      reboot:
      when: reboot_required_centos.rc == 1 and ansible_distribution in ["Fedora", "RHEL", "CentOS"]
